language: node_js 
node_js:
  - 12 # Level of Node.js to use
script:
  - npm run build
  - npm run export
  - touch out/.nojekyll 
deploy:
  provider: pages 
  skip_cleanup: true 
  github_token: $github_token 
  local_dir: out 
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|main)$


